apps/article/models.py
from exts import db
from datetime import datetime

class Article_type(db.Model):
    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    type_name = db.Column(db.String(20), nullable=False)

    # relationship
    articles = db.relationship('Article', backref='article_type')

class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(50), nullable=False) # 标题
    content = db.Column(db.Text, nullable=False)     # 内容
    pdatetime = db.Column(db.DateTime, default=datetime.now) # 发表时间
    click_num = db.Column(db.Integer, default=0)  # 阅读量
    save_num = db.Column(db.Integer, default=0)   # 收藏数
    love_num = db.Column(db.Integer, default=0)   # 点赞数
    # 外键   外键在多这一侧定义 同步到数据库
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    type_id = db.Column(db.Integer, db.ForeignKey('article_type.id'))
    # relationship
    comments = db.relationship('Comment', backref='article')
# 评论
class Comment(db.Model):
    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    article_id = db.Column(db.Integer, db.ForeignKey('article.id'))
    comment = db.Column(db.String(255), nullable=False)
    cdatetime = db.Column(db.DateTime, default=datetime.now)

apps/article/views.py
from flask import Blueprint, render_template, request, g, redirect, url_for,jsonify,session
from apps.user.models import User
from apps.article.models import *
from exts import db

article_bp = Blueprint('article', __name__, url_prefix='/article')


# 自定义过滤器 过滤
@article_bp.app_template_filter('cdecode')
def content_cdecode(content):
    content = content.decode('utf-8')
    return content

@article_bp.route('/publish', methods=['POST','GET'])
def publish_article():
    if request.method == 'POST':
        title = request.form.get('title')
        type_id = request.form.get('type')
        content = request.form.get('content')
        article = Article()
        article.title = title
        article.type_id = type_id
        article.content = content
        article.user_id = g.user.id
        db.session.add(article)
        db.session.commit()
        return redirect(url_for('user.index'))
# 文章详情
@article_bp.route('/detail')
def article_detail():
    article_id =  request.args.get('aid')
    article = Article.query.get(article_id)
    types = Article_type.query.all()
     # 登录用户
    user = None
    user_id = session.get('uid',None)
    if user_id:
        user = User.query.get(user_id)
    return render_template('article/detail.html',article=article, types=types, user=user)

@article_bp.route('/save')
def article_save():
    article_id = request.args.get('aid')
    article = Article.query.get(article_id)
    tag = request.args.get('tag')
    if (tag == '0'):
        article.save_num += 1
    else:
        article.save_num -= 1
    db.session.commit()
    return jsonify(num=article.save_num)


@article_bp.route('/love')
def article_love():
    article_id = request.args.get('aid')
    article = Article.query.get(article_id)
    tag = request.args.get('tag')
    if (tag == '0'):
        article.love_num += 1
    else:
        article.love_num -= 1
    db.session.commit()
    return jsonify(num=article.love_num)

@article_bp.route('/article_comment',methods=['GET','POST'])
def article_comment():
    if request.method == 'POST':
        pass

apps/templates/article/add_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加文章</title>
</head>
<body>
<form action="{{ url_for('article.article_publish') }}" method="post">
    <p><input type="text" name="title" placeholder="文章标题"></p>
    <p>
        <textarea name="content" cols="30" rows="10" placeholder="文章内容">
        </textarea>
    </p>
    <p>
        用户：
        <select name="uid" id="">
            <option value="0">请选择用户</option>
            {% for user in users %}
                <option value={{ user.id}}>{{ user.username }}</option>
            {% endfor %}
            
        </select>

    </p>
    <p><input type="submit" value="添加文章"></p>
</form>

</body>
</html>

apps/templates/article/all.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>展示文章</title>
    <style>
        #container{
            border: 1px solid brown;
            margin-bottom: 10px;
            padding: 5px;
        }
    </style>
</head>
<body>
{% for article in articles %}
<div id="container">
    <p>
        <h3>{{ article.title }}</h3>
        <div>作者：{{ article.user.username }}</div>
    </p>
    <p>
        {{ article.content }}
    </p>
    <div>{{ article.pdatetime }}</div>
</div>

{% endfor %}



</body>
</html>

apps/templates/article/all1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for article in user.articles %}
<div>
    <p>
        <h3>{{ article.title }}</h3>
        <div>作者：{{ user.username }}</div>
    </p>
    <p>
        {{ article.content }}
    </p>
    <div>{{ article.pdatetime }}</div>
</div>
{% endfor %}


</body>
</html>

apps/templates/article/detail.html
{% extends 'base.html' %}
{% block title %}
    文章详情
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
    #container{
        width:1000px;
        margin: 0 auto;
    }
    #container p{
        overflow: auto;
    }
    #left{
        float:left;

    }
    #right{
        float:right;
    }
    #content{
        margin-top: 30px;
    }
    </style>

{% endblock %}

{% block newcontent %}
    <div id="container">
        <div id="detail">
            <h2>{{ article.title }}</h2>
            <p>
            <div id="left">
                作者：{{ article.user.username }}&nbsp;&nbsp;&nbsp;&nbsp;
                发布时间：{{ article.pdatetime }}</div>
            <div id="right">
                <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                <span tag="0">{{ article.love_num }}</span>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
                <span tag="0">{{ article.save_num }}</span>
            </div></p>
            <div id="content">{{ article.content|cdecode|safe }}</div>




        </div>

    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
    $(function () {
        // 点赞
        $('.glyphicon-heart').click(function () {
            let $this = $(this);
            let tag = $this.next('span').attr('tag');
            // 处理 点击事件的路由，传递的数据，返回的结果为data 通过function对结果进行处理
           $.get('{{ url_for('article.article_love') }}',{aid:{{article.id}},tag:tag},function (data) {
               $this.next('span').text(data.num);
           })
            if(tag=='1'){
                $this.css({color:'black'})
                $this.next('span').attr('tag','0')
            }else{
                $this.css({color:'red'})
                $this.next('span').attr('tag','1')
            }
        });
        // 收藏
        $('.glyphicon-star-empty').click(function () {
            let $this = $(this);
            let tag = $this.next('span').attr('tag');
            // 处理 点击事件的路由，传递的数据，返回的结果为data 通过function对结果进行处理
           $.get('{{ url_for('article.article_save') }}',{aid:{{article.id}},tag:tag},function (data) {
               $this.next('span').text(data.num);
           })
            if(tag=='1'){
                $this.css({color:'black'})
                $this.next('span').attr('tag','0')
            }else{
                $this.css({color:'red'})
                $this.next('span').attr('tag','1')
            }


        });
        
    })
    </script>

{% endblock %}