apps/user/models.py
from exts import db
from datetime import datetime

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(20), nullable=False)
    password = db.Column(db.String(64), nullable=False)
    phone = db.Column(db.String(11), unique=True, nullable=False)
    email = db.Column(db.String(30))
    icon = db.Column(db.String(100))  # 头像地址
    isdelete = db.Column(db.Boolean, default=False)  # 逻辑删除
    rdatetime = db.Column(db.DateTime, default=datetime.now)

    # 在查找user的文章列表时使用user.articles;backref是反向引用
# 根据文章找文章的作者时通过该反向引用来实现，直接使用article.user得到作者对象
    articles = db.relationship('Article', backref='user')

    def __str__(self):
        return self.username

class Photo(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    photo_name = db.Column(db.String(50),nullable=False)
    photo_datetime = db.Column(db.DateTime, default=datetime.now)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'),nullable=False)

    def __str__(self):
        return self.photo_name

apps/article/views.py
from flask import Blueprint, render_template, request, g, redirect, url_for,jsonify,session
from apps.user.models import User
from apps.article.models import *
from exts import db

article_bp = Blueprint('article', __name__, url_prefix='/article')


# 自定义过滤器 过滤
@article_bp.app_template_filter('cdecode')
def content_cdecode(content):
    content = content.decode('utf-8')
    return content

@article_bp.route('/publish', methods=['POST','GET'])
def publish_article():
    if request.method == 'POST':
        title = request.form.get('title')
        type_id = request.form.get('type')
        content = request.form.get('content')
        article = Article()
        article.title = title
        article.type_id = type_id
        article.content = content
        article.user_id = g.user.id
        db.session.add(article)
        db.session.commit()
        return redirect(url_for('user.index'))
# 文章详情
@article_bp.route('/detail')
def article_detail():
    article_id =  request.args.get('aid')
    article = Article.query.get(article_id)
    types = Article_type.query.all()
     # 登录用户
    user = None
    user_id = session.get('uid',None)
    if user_id:
        user = User.query.get(user_id)
    return render_template('article/detail.html',article=article, types=types, user=user)

@article_bp.route('/save')
def article_save():
    article_id = request.args.get('aid')
    article = Article.query.get(article_id)
    tag = request.args.get('tag')
    if (tag == '0'):
        article.save_num += 1
    else:
        article.save_num -= 1
    db.session.commit()
    return jsonify(num=article.save_num)


@article_bp.route('/love')
def article_love():
    article_id = request.args.get('aid')
    article = Article.query.get(article_id)
    tag = request.args.get('tag')
    if (tag == '0'):
        article.love_num += 1
    else:
        article.love_num -= 1
    db.session.commit()
    return jsonify(num=article.love_num)

@article_bp.route('/article_comment',methods=['GET','POST'])
def article_comment():
    if request.method == 'POST':
        pass

apps/user/views.py
from flask import Blueprint, render_template, url_for, redirect, request, jsonify, session, g
from .models import *
from exts import db
import os
from .smssend import SmsSendAPIDemo
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename
from settings import Config
from apps.article.models import Article_type, Article
from apps.utils.util import upload_qiniu

user_bp = Blueprint('user', __name__, url_prefix='/user')
required_login_list = ['/user/center', '/user/edit', '/article/publish','/user/upload_photo']

@user_bp.route('/')
def index():
    # cookie获取方式
    # uid = request.cookies.get('uid', None)
    # session的获取,session底层默认获取
    uid = session.get('uid')
    page = int(request.args.get('page', 1))
    # 无论是否登录都要显示文章列表和文章分类列表
    types = Article_type.query.all()
    # 分页
    # articles = Article.query.order_by(-Article.pdatetime).all()
    pagination = Article.query.order_by(-Article.pdatetime).paginate(page=page, per_page=2)

    # Pagination对象属性
    # pagination.items 当前页面中的记录
    # pagination.page 当前页数
    # pagination.prev_num # 上一页的页码数
    # pagination.next_num # 下一页的页码数
    # pagination.has_prev # 是否有上一页
    # pagination.has_next # 是否有下一页
    # pagination.pages  # 总页数
    # pagination.total  # 总的记录数

    if uid:
        user = User.query.get(uid)
        return render_template('user/index.html', user=user, types=types, pagination=pagination)
    else:
        return render_template('user/index.html', types=types, pagination=pagination)
# 用户注册
@user_bp.route('/register', methods=['POST','GET'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        repassword = request.form.get('repassword')
        phone = request.form.get('phone')
        email = request.form.get('email')
        if password == repassword:
            user =User()
            user.username = username
            user.password = generate_password_hash(password)
            user.phone = phone
            user.email = email
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('user.index'))
    return  render_template('user/register.html')

# 手机号码验证
@user_bp.route('/checkphone')
def check_phone():
    phone = request.args.get('phone')
    user = User.query.filter(User.phone==phone).all()
    # code:400 不能用  200 ：能用
    if len(user) > 0:
        print(user)
        return jsonify(code=400, msg='此号码已被注册')   # ajax必须返回json格式
    else:
        return jsonify(code=200, msg='此号码可用')

# 用户登录
@user_bp.route('/login', methods=['POST','GET'])
def login():
    if request.method == 'POST':
        # 判断是用户名登录f=1 还是手机号登录f=2
        f = request.args.get('f')
        if f == '1':
            username = request.form.get('username')
            password = request.form.get('password')
            users = User.query.filter(User.username == username).all()
            print(len(users))
            for user in users:
                flag = check_password_hash(user.password, password)
                if flag:
                    # cookie机制实现
                    # response = redirect(url_for('user.index'))
                    # response.set_cookie('uid', str(user.id),max_age=1800) # expires 过期时间
                    # return response
                    # session实现，session当成字典使用
                    session['uid'] = user.id
                    return redirect(url_for('user.index'))

                else:
                    return render_template('user/login.html', msg='用户名或者密码有误')
        elif f == '2': #手机号码登录
            code = request.form.get('code')
            phone = request.form.get('phone')
            # 验证码 先验证是否正确
            valid_code = session.get(phone)
            if code == valid_code:
                user = User.query.filter(User.phone == phone).first()
                if user:
                    # 登录成功 使用session机制
                    session['uid'] = user.id
                    return redirect(url_for('user.index'))
                else:
                    return render_template('user/login.html', msg='此号码未注册')
            else:
                return render_template('user/login.html', msg='验证码有误')

    else:
        return render_template('user/login.html')

# 退出
@user_bp.route('/logout')
def logout():
    # 1. cookie删除方式
    # response = redirect(url_for('user.index'))
    # 通过response对象的delete_cookie(key), key就是要删除的cookie的key
    # response.delete_cookie('uid')
    # 2. session的方式
    # del session['uid']
    session.clear()
    return redirect(url_for('user.index'))

# 发送短信息
@user_bp.route('/sendMsg', methods=['POST', 'GET'])
def send_message():
    phone = request.args.get('phone')
    # 补充 验证手机号码 是否注册，去数据库查询 ，若手机号码注册过则进行验证码的发送，否则返回此号码未注册
    SECRET_ID = "your_secret_id"  # 产品密钥ID，产品标识
    SECRET_KEY = "your_secret_key"  # 产品私有密钥，服务端生成签名信息使用，请严格保管，避免泄露
    BUSINESS_ID = "your_business_id"  # 业务ID，易盾根据产品业务特点分配
    api = SmsSendAPIDemo(SECRET_ID, SECRET_KEY, BUSINESS_ID)
    params = {
        "mobile": phone,
        "templateId": "10084",
        "paramType": "json",
        "params": "json格式字符串"
    }
    ret = api.send(params)
    session[phone] = '189075'  # 得到的验证码  将其放入session中，因为谁请求就会为谁分配一个session空间
    return jsonify(code=200, msg='短信发送成功')
    # if ret is not None:
    #     if ret["code"] == 200:
    #         taskId = ret["data"]["taskId"]
    #         print("taskId = %s" % taskId)
    #         session[phone] = '189075'
    #         return jsonify(code=200, msg='短信发送成功')
    #     else:
    #         print ("ERROR: ret.code=%s,msg=%s" % (ret['code'], ret['msg']))
    #         return jsonify(code=400, msg='短信发送失败')

# 用户中心
@user_bp.route('/center')
def user_center():
    # id = session.get('uid')
    # user = User.query.get(id)
    # return render_template('user/center.html',user=user)
    types = Article_type.query.all()
    photos = Photo.query.filter(Photo.user_id == g.user.id).all()
    return render_template('user/center.html', user=g.user, types=types,photos=photos)

@user_bp.before_app_request
def before_request():
    print('before request', request.path)
    if request.path in required_login_list:
        id = session.get('uid')
        if not id:
            return render_template('user/login.html')
        else:
            user = User.query.get(id)  #
            g.user = user  # g对象 是在本次请求中产生的对象
# 图片的扩展名
ALLOWED_EXTENSIONS = ['jpg','png','gif','bmp']
# 用户信息修改
@user_bp.route('/edit', methods=['POST', 'GET'])
def user_edit():
    if request.method == 'POST':
        username = request.form.get('username')
        phone = request.form.get('phone')
        email = request.form.get('email')
        # print(email)
        # 只要有文件(图片)， 获取方式必须使用request.files.get(name)
        icon = request.files.get('icon')

        # print('================>',icon)
        # FileStorage对象
        # 属性：filename 用户获取文件（图片）的名字
        # 方法：save(保存路径)
        icon_name = icon.filename
        print('+++++++++++++++++++++', icon_name)
        suffix = icon_name.rsplit('.')[-1]
        if suffix in ALLOWED_EXTENSIONS:
            icon_name = secure_filename(icon_name) #保证文件名符合python命名规则
            file_path = os.path.join(Config.UPLOAD_ICON_DIR, icon_name)
            icon.save(file_path)
            # 保存成功
            # 存数据库时 icon存相对路径
            user = g.user
            user.username = username
            user.phone = phone
            user.email = email
            path = 'upload/icon'
            user.icon = path + '/' + icon_name
            # print(os.path.join(path, icon_name))
            db.session.commit()
            # print('+++++++++++++',user.icon)
            # print(url_for('static', filename=user.icon ))
            return redirect(url_for('user.user_center'))
        else:
            return render_template('user/center.html', user=g.user, msg='必须扩展名是png,jpg,gif,bmp')
        # print(icon_name)
        # 查询 手机号码 如果已有该手机号码，则提示
        # 使用ajax 当失去焦点blur时间 验证手机号 采用该种方式时，就不必从数据库中
        # users = User.query.all()
        # for user in users:
        #     if user.phone == phone:
        #         return render_template('user/center.html', msg='此号码已被注册')

    return render_template('user/center.html', user=g.user)

# 自定义过滤器 过滤
@user_bp.app_template_filter('decode')
def content_cdecode(content):
    content = content.decode('utf-8')
    return content[:200]

@user_bp.route('/upload_photo', methods=['POST','GET'])
def upload_photo():
    # 获取上传的内容
    photo = request.form.get('photo') # FileStorage
    # photo.filename,   photo.save(path) 保存到本地
    ret, info = upload_qiniu(photo)
    if info.status_code == 200:
        photo = Photo()
        photo.photo_name = ret['key']
        photo.user_id = g.user.id
        db.session.add(photo)
        db.session.commit()
        return '上传成功'
    return '上传失败'

apps/templates/user/center.html
{% extends 'base.html' %}
{% block title %}

{% endblock %}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/center.css') }}">

{% endblock %}

{% block newcontent %}
    <div id="container">
        <div id="left">
            <p>用户信息修改</p>
            <p>发表文章</p>
            <p>管理相册</p>
            <p>管理留言</p>
            <p>关于我设置</p>
        </div>
        <div id="right">
            <div class="right1">
                <h2>用户信息修改</h2>
                {# 带文件上传必填enctype               #}
                <form action="{{ url_for('user.user_edit') }}" method="post" enctype="multipart/form-data">
                    <p>
                        <img src="{% if user.icon %} {{ url_for('static', filename=user.icon ) }} {% else %} {{ url_for('static', filename='images/touxiang.jpg' ) }} {% endif %}"
                             alt="" width="90" height="100">
                        {#                        <img src="{{ url_for('static', filename='images/touxiang.jpg' ) }}" alt="" width="90" height="100">#}
                    </p>
                    <p><input type="file" id="exampleInputFile" name="icon" alt="更换"></p>


                    <p><input type="text" class="form-control" id="InputUsername" name="username"
                              value="{{ g.user.username }}"></p>
                    <p><input type="text" class="form-control" id="InputPhone" name="phone" value="{{ g.user.phone }}">
                        <span></span></p>
                    <p><input type="text" class="form-control" id="InputEmail" name="email" value="{{ g.user.email }}">
                    </p>

                    <p>
                        <button type="submit" class="btn btn-primary">用户信息修改</button>
                    </p>
                </form>
            </div>
            <div class="right1" style="padding-top: 20px;">
                <form action="{{ url_for('article.publish_article') }}" method="post">
                    <p>
                        <input type="text" class="form-control" id="InputTitle" name="title"
                               placeholder="请输入文章标题">
                    </p>
                    <p>
                        <select name="type" class="form-control">
                            <option value="0">请选择文章分类</option>
                            {% for type in types %}
                                <option value="{{ type.id }}">{{ type.type_name }}</option>
                            {% endfor %}
                        </select>
                    </p>
                    <p>
                        <textarea name="content" class="mytextarea">
                        </textarea>
                    </p>
                <p style="text-align: right;">
                    <button type="submit" class="btn btn-primary">发表文章</button>
                </p>
                </form>
            </div>
            <div class="right1">
                <form action="{{ url_for('user.upload_photo') }}" method="post" enctype="multipart/form-data" class="form-inline">
                    <input type="file" name="photo" class="form-control">
                    <input type="submit" value="上传相册" class="btn btn-default">
                </form>
                <div class="row">
                    <div class="col-sm-12">
                        <h3>我的相册</h3>
                        <div class="row">
{#                            {% for photo in photos %}#
{#                             <div class="col-xs-8 col-sm-4">#}
{#                                <img src="七牛云存储共有空间域名/{{ photo.photo_name }}" alt="" class="img-rounded image">#}
{#                            </div>#}
{#                            {% endfor %}#}
                            <div class="col-xs-8 col-sm-4">
                                <img src="{{ url_for('static',filename='images/touxiang.jpg') }}" alt="" class="img-rounded image">
                            </div>
                            <div class="col-xs-8 col-sm-4">
                                <img src="{{ url_for('static',filename='images/touxiang.jpg') }}" alt="" class="img-rounded image">
                            </div>
                            <div class="col-xs-8 col-sm-4">
                                <img src="{{ url_for('static',filename='images/touxiang.jpg') }}" alt="" class="img-rounded image">
                            </div>
                            <div class="col-xs-8 col-sm-4">
                                <img src="{{ url_for('static',filename='images/touxiang.jpg') }}" alt="" class="img-rounded image">
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="right1">
                管理留言
            </div>
            <div class="right1">
                关于我设置
            </div>


        </div>

    </div>

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static',filename='tinymce/tinymce.min.js') }}"></script>
    <script>

        $(function () {
            // 设置富文本
            tinymce.init({
                selector: '.mytextarea',
                height: 400,
                plugins: 'quickbars emoticons',
                inline: false,
                toolbar: true,
                menubar: true,
                quickbars_selection_toolbar: 'bold italic | link h2 h3 blockquote',
                quickbars_insert_toolbar: 'quickimage quicktable',

            });

            //显示隐藏登录方式
            $(".right1").hide();
            $(".right1").first().show();
            $("#left p").each(function (i) {
                $(this).click(function () {
                    $('#left p').css({'background-color': 'rgba(30, 150, 196, 0.94)'});
                    $(this).css({'background-color': 'skyblue', 'box-shadow': '5px 5px 5px deepskyblue'});

                    $(".right1").hide();
                    $(".right1").eq(i).show();
                })
            });
            // 发送验证码
            $('#btnCheck').click(function () {
                let phone = $('#inputPhone').val();
                let span_ele = $('#inputPhone').next('span');
                span_ele.css({"color": "#ff0011", "font-size": "12px"});
                if (phone.length == 11) {
                    // 发送ajax请求
                    $.get('{{ url_for('user.send_message') }}', {phone: phone}, function (data) {
                        // 发送验证码结果
                        if (data.code == 200) {
                            alert('短信发送成功请查收');
                        } else {
                            alert(data.msg);
                        }
                    });
                }
                else {
                    span_ele.text('必须输入11位手机号码')
                }
            });
        })
    </script>
{% endblock %}

apps/templates/user/index.html
{% extends 'base.html' %}
{% block title %}博客首页{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 900px;
            margin: 0 auto;
        }

        .article {
            width: 90%;
            margin: 20px auto;
            padding: 5px 10px;
            background-color: rgba(131, 202, 227, 0.7);
            border-bottom: 1px solid gray;
        }

        .article p {
            font-size: 14px;
                rgba(75, 75, 74, 1.0);
        }

        .article h4 a {
            color: rgba(80, 80, 70, 1.00);
        }

        .article h4 a:hover {
            color: black;
        }

        .article div span {
            margin-left: 20px;
        }

        .article div {
            margin-bottom: 18px;
        }
    </style>

{% endblock %}

{% block newcontent %}
    <div id="container">
        {% for article in pagination.items %}
            <div class="article"><h4><a href="{{ url_for('article.article_detail') }}?aid={{ article.id }}">{{ article.title }}</a></h4>
            <p>
                <span>作者：{{ article.user.username }}</span><br><br>
                <div>{{ article.content | decode |safe }}</div>
            </p>
            <div>
                <span style="margin-left: 0;">发布时间：{{ article.pdatetime }}</span>
                <span>收藏：{{ article.save_num }}</span>
                <span>点击量：{{ article.click_num }}</span>
                <span>点赞数：{{ article.love_num }}</span>
            </div>
            </div>
        {% endfor %}
        <nav aria-label="Page navigation" class="col-md-offset-5">
          <ul class="pagination">
            <li {% if not pagination.has_prev %}class="disabled" {% endif %}>
                <a href="{{ url_for('user.index') }}?page={{ pagination.prev_num }}" aria-label="Previous">&laquo;
                </a>
            </li>
              {% for page_num in range(1, pagination.pages + 1) %}
                  <li {% if  pagination.page == page_num%}
                  class="active" {% endif %}><a href="{{ url_for('user.index') }}?page={{ page_num }}">{{ page_num }}</a></li>
              {% endfor %}
           <li {% if  not pagination.has_next%}class="disabled"{% endif %} >
               <a href="{{ url_for('user.index') }}?page={{ pagination.next_num }}" aria-label="Next">&raquo;</a>
           </li>
          </ul>
        </nav>
    </div>
{% endblock %}

apps/templates/user/login.html
{% extends 'base.html' %}
{% block title %}登录{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container h1 {
            padding-bottom: 50px;
            font-weight: normal;
           
            padding-left: 100px;
        }
        #container {
            width: 500px;
            margin: 0 auto;
            height: 400px;
            padding-right: 50px;
        }

        #tab span {
            display: inline-block;
            width: 120px;
            text-align: center;
            cursor: default;
            color: #f3f3f3;
            font-size: 15px;
            margin-bottom: 10px;
        }

        #tips {
            color: red;
            font-size: 14px;

        }
    #btnCheck{
        width: 140px;
    }

    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
        <h1>用户登录</h1>
        <div id="tab">
            <span>用户名 / 密码</span> | <span>手机验证码</span>
            <p id="tips">{{ msg }}</p>
        </div>
        <div class="logintab">
            <form class="form-horizontal" method="post" action="{{ url_for('user.login') }}?f=1">
                <div class="form-group">
                    <div class="col-sm-10">
                        <input type="text" name="username" class="form-control" id="inputUsername" placeholder="用户名">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-10">
                        <input type="password" name="password" class="form-control" id="inputPassword" placeholder="密码">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-info ">登 录</button>
                        <button type="reset" class="btn btn-info col-sm-offset-5">重 置</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="logintab">
            <form class="form-horizontal" method="post" action="{{ url_for('user.login') }}?f=2">
                <div class="form-group">
                    <div class="col-sm-10">
                        <input type="text" name="phone" class="form-control" id="inputPhone" placeholder="输入手机号">
                        <span></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-6">
                        <input type="text" name="code" class="form-control" id="inputCode" placeholder="输入验证码">
                    </div>
                    <div class="col-sm-1">
                        <input type="button" id="btnCheck" class="btn btn-info" value="发送验证码"/>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-info ">登 录</button>
                        <button type="reset" class="btn btn-info col-sm-offset-5">重 置</button>
                    </div>
                </div>


            </form>
        </div>
    </div>

{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>

        $(function () {
            //显示隐藏登录方式
            $(".logintab").hide();
            $(".logintab").first().show();
            $("#tab span").each(function (i) {
                $(this).click(function () {
                    $(".logintab").hide();
                    $(".logintab").eq(i).show();
                })
            });
            // 发送验证码
            $('#btnCheck').click(function () {
                let phone = $('#inputPhone').val();
                let span_ele = $('#inputPhone').next('span');
                span_ele.css({ "color": "#ff0011", "font-size": "12px" });
                if(phone.length == 11){
                    // 发送ajax请求
                    $.get('{{ url_for('user.send_message') }}',{phone:phone},function (data) {
                        // 发送验证码结果
                        if(data.code == 200){
                            alert('短信发送成功请查收');
                        }else {
                            alert(data.msg);
                        }
                    });
                }
                else{
                    span_ele.text('必须输入11位手机号码')
                }
            });
        })
    </script>
{% endblock %}

apps/templates/user/register.html
{% extends 'base.html' %}

{% block title %} 用户注册
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        {# padding是内边距
        {#margin是外边距 #}
        #container h1 {
            padding-bottom: 20px;
            font-weight: normal;
        }

        #container {
            width: 500px;
            margin: 0 auto;
            height: 400px;
        }
    .navbar{

    }
    </style>

{% endblock %}
{% block newcontent %}
    <div style="background-image: url('{{ url_for('static',filename='images/register.jpg') }}')">

        <div id="container">
            <h1 align="center">用户注册</h1>
            <form class="form-horizontal" method="post" action="{{ url_for('user.register') }}">
                <div class="form-group">
                    <label for="inputUsername" class="col-md-2 control-label">用户名</label>
                    <div class="col-sm-10">
                        <input type="text" name="username" class="form-control" id="inputUsername" placeholder="用户名">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword" class="col-sm-2 control-label">密码</label>
                    <div class="col-sm-10">
                        <input type="password" name="password" class="form-control" id="inputPassword" placeholder="密码">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputConfirm" class="col-sm-2 control-label">确认密码</label>
                    <div class="col-sm-10">
                        <input type="password" name="repassword" class="form-control" id="inputConfirm"
                               placeholder="确认密码">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPhone" class="col-sm-2 control-label">手机号码</label>
                    <div class="col-sm-10">
                        <input type="text" name="phone" class="form-control" id="inputPhone" placeholder="手机号码">
                        <span></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail" class="col-sm-2 control-label">邮箱</label>
                    <div class="col-sm-10">
                        <input type="email" name="email" class="form-control" id="inputEmail" placeholder="邮箱">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-info col-sm-5" style="font-family:  微软雅黑">注&nbsp;册</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
{% endblock %}
{# 添加js脚本 #}
{% block scripts %}
    {{ super() }}
    <script>
    $('#inputPhone').blur(function () {
        let phone = $(this).val();
        let span_ele = $(this).next('span');
        span_ele.css({ "color": "#ff0011", "font-size": "12px" });
        if (phone.length == 11){
            span_ele.text('');
            //# 发送ajax请求 get() get请求 参数分别为：路由,发送的参数，function 发送成功之后调用的函数，
            // data接收发送后返回的结果
            $.get('{{ url_for('user.check_phone') }}', {phone: phone},function (data) {
            //{#console.log(data);#}
                if(data.code != 200){
                    span_ele.text(data.msg);
                }
            })
        }else {
            span_ele.text('手机格式错误');
        }


    })
    </script>

{% endblock %}